#!/usr/bin/with-contenv sh

if [ ! -f "/etc/conf/aria2/aria2.session" ]; then
  touch /etc/conf/aria2/aria2.session
fi

if ! [[ -z "${ARIA2_RPC_SECRET}" ]]; then
  echo "Enabled rpc secret"
  sed -i "s/^#\(rpc-secret=\)\(.*\)$/\1${ARIA2_RPC_SECRET}/" /etc/conf/aria2/aria2.conf
fi

/etc/conf/aria2/update_trackers.sh
